platform :ios, '9.0'

target 'TCZoomingImageView' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TCZoomingImageView

  pod 'TCZoomingImageViewSwift'

end
