# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TCZoomingImageView' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TCZoomingImageView

  target 'TCZoomingImageViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TCZoomingImageViewUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'TCZoomingImageView'

  end

end
